### ISSUE TITLE
Editing not showing real value

### ISSUE THREAD

**Issue by arturjnt** [arturjnt/kulut#1]
Editing not showing real value if it's a combined expense & combined expenses checkbox is unticked

**Comment by mrcchef** [comment]
hey, I would love to help you!!

Can you give a brief of your problem?

**Comment by arturjnt** [comment]
Hello @mrcchef I've done a commit today that has fixed the issue. Feel free to review the commit and leave comments if you see something.

**Comment by mrcchef** [comment]
Ok, Sure.
